### ISSUE TITLE
調整コントローラーを折り畳みたい

### ISSUE THREAD

**Issue by pandanoir** [thr3a/mantine-cheatsheets#23]
Color や radius、size などの項目が全て出ていると、特にスマホで閲覧した際に見づらいです。そのため折り畳めるようにしてコンポーネントを調整したい時だけ開くようにしたいです

**Comment by thr3a** [comment]
各コンポーネントは [@mantine/ds](https://www.npmjs.com/package/@mantine/ds) のデモコンポーネントを自動的に表示しています。
そのコンポーネントでは、コードの非表示オプションはありますが調整UIを非表示にするオプションが存在しないため難しいです。
